@extends('layouts.app')

@section('content')
    @vite(['resources/css/minijuegos.css'])

    <div class="hub-background"></div>

    <div class="container mx-auto px-4">
        <div class="game-area">
            <a href="{{ route('minijuego.index') }}" class="btn-back"><i class="fas fa-arrow-left"></i> Volver al Hub</a>
            
            <div class="game-header">
                <h2>El Triler Voltorb</h2>
                <p>Encuentra a Pikachu. ¡Cuidado con el Voltorb!</p>
            </div>

            <div class="triler-container" id="triler-board">
                <!-- Pokéballs generated by JS -->
            </div>
            
            <div class="my-4">
                <button id="btn-start" class="btn-play" style="width: auto; padding: 0.8rem 2rem;">Mezclar Pokéballs (Coste: 10 <i class="fas fa-coins"></i>)</button>
            </div>

            <h3 id="response" class="text-2xl font-bold my-2" style="height: 32px;"></h3>
            <p id="feedback" class="font-bold"></p>
        </div>
    </div>

    <script>
        const board = document.getElementById("triler-board");
        const btnStart = document.getElementById("btn-start");
        const responseEl = document.getElementById("response");
        const feedbackEl = document.getElementById("feedback");
        
        let isPlaying = false;
        let isShuffling = false;
        let winningIndex = 0;
        let balls = [];

        function initBoard() {
            board.innerHTML = "";
            balls = [];
            for(let i=0; i<3; i++){
                const wrapper = document.createElement("div");
                wrapper.className = "pokeball-wrapper";
                wrapper.dataset.index = i;
                
                const ball = document.createElement("div");
                ball.className = "pokeball";
                
                const reward = document.createElement("div");
                reward.className = "hidden-reward";
                
                wrapper.appendChild(ball);
                wrapper.appendChild(reward);
                
                wrapper.addEventListener("click", function() { selectBall(this); });
                
                board.appendChild(wrapper);
                balls.push(wrapper);
            }
        }

        async function startGame() {
            if (isPlaying || isShuffling) return;
            
            responseEl.textContent = "";
            feedbackEl.textContent = "";

            isPlaying = true;
            isShuffling = true;
            board.style.pointerEvents = "none";
            btnStart.disabled = true;

            // Aseguramos que estén cerradas de rondas anteriores
            balls.forEach(wrapper => wrapper.classList.remove("open"));
            await new Promise(r => setTimeout(r, 400));
            
            // Generate Pikachu (win)
            winningIndex = Math.floor(Math.random() * 3);
            
            balls.forEach((wrapper, index) => {
                wrapper.dataset.isWinner = (index === winningIndex) ? "true" : "false";
                const reward = wrapper.querySelector(".hidden-reward");
                if (index === winningIndex) {
                    reward.style.backgroundImage = "url('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png')"; // Pikachu
                } else {
                    reward.style.backgroundImage = "url('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png')"; // Voltorb
                }
            });

            btnStart.textContent = "¡Atento a Pikachu!";
            
            // Mostramos el contenido para memorizar
            balls.forEach(wrapper => wrapper.classList.add("open"));
            await new Promise(r => setTimeout(r, 1500));
            
            // Volvemos a ocultar
            balls.forEach(wrapper => wrapper.classList.remove("open"));
            await new Promise(r => setTimeout(r, 500));

            btnStart.textContent = "Mezclando...";
            
            // Animation sequence
            for (let i = 0; i < 5; i++) {
                await swapBalls();
            }
            
            isShuffling = false;
            board.style.pointerEvents = "auto";
            btnStart.textContent = "¡Elige una Pokéball!";
        }

        function swapBalls() {
            return new Promise(resolve => {
                const idx1 = Math.floor(Math.random() * 3);
                let idx2 = Math.floor(Math.random() * 3);
                while(idx1 === idx2) {
                    idx2 = Math.floor(Math.random() * 3);
                }
                
                const b1 = balls[idx1];
                const b2 = balls[idx2];
                
                // FLIP Animation: Get initial positions
                const rect1 = b1.getBoundingClientRect();
                const rect2 = b2.getBoundingClientRect();

                // Calculate delta
                const deltaX = rect2.left - rect1.left;
                const deltaY = rect2.top - rect1.top;

                // Apply transition
                b1.style.transition = 'transform 0.4s ease-in-out';
                b2.style.transition = 'transform 0.4s ease-in-out';
                
                b1.classList.add("shake");
                b2.classList.add("shake");
                
                // Translate visually
                b1.style.transform = `translate(${deltaX}px, ${deltaY}px)`;
                b2.style.transform = `translate(${-deltaX}px, ${-deltaY}px)`;
                
                setTimeout(() => {
                    b1.classList.remove("shake");
                    b2.classList.remove("shake");
                    
                    // Remove transforms and transitions
                    b1.style.transition = '';
                    b2.style.transition = '';
                    b1.style.transform = '';
                    b2.style.transform = '';
                    
                    // DOM swap
                    const sibling1 = b1.nextSibling === b2 ? b1 : b1.nextSibling;
                    b2.parentNode.insertBefore(b1, b2);
                    b1.parentNode.insertBefore(b2, sibling1);
                    
                    // Update array references
                    const temp = balls[idx1];
                    balls[idx1] = balls[idx2];
                    balls[idx2] = temp;
                    
                    resolve();
                }, 400);
            });
        }

        async function selectBall(clickedWrapper) {
            if (!isPlaying || isShuffling) return;
            
            clickedWrapper.classList.add("open");
            
            // Did we win?
            const isWinner = clickedWrapper.dataset.isWinner === "true";
            
            isPlaying = false;
            
            // Open others after a delay
            setTimeout(() => {
                balls.forEach(b => b.classList.add("open"));
            }, 1000);

            let amount = isWinner ? 30 : -10;

            try {
                const res = await fetch('{{ route('minijuego.reward') }}',{
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
                        'Accept': 'application/json'
                    },
                    body: JSON.stringify({ amount: amount, game: 'triler' }) // Net gain 20 (30 - 10 cost)
                });
                
                const data = await res.json();
                
                if (isWinner) {
                    responseEl.textContent = "¡Encontraste a Pikachu!";
                    responseEl.style.color = "#4ade80";
                    if(data.success){
                        feedbackEl.textContent = data.message;
                        feedbackEl.style.color = "#4ade80";
                        if(data.monedas !== undefined){
                            const walletEl = document.getElementById("wallet");
                            if(walletEl) walletEl.textContent = data.monedas;
                            createCoinAnimation();
                        }
                    } else {
                        feedbackEl.textContent = data.message;
                    }
                } else {
                    responseEl.textContent = "¡Oh no, era un Voltorb!";
                    responseEl.style.color = "#f87171";
                    
                    if (data.success) {
                        feedbackEl.textContent = data.message;
                        feedbackEl.style.color = "#f87171";
                        if(data.monedas !== undefined){
                            const walletEl = document.getElementById("wallet");
                            if(walletEl) walletEl.textContent = data.monedas;
                        }
                    } else {
                        feedbackEl.textContent = "Has perdido 10 monedas.";
                        feedbackEl.style.color = "#f87171";
                    }
                }
            } catch(e) {
                console.error(e);
            }
            
            setTimeout(() => {
                btnStart.disabled = false;
                btnStart.textContent = "Volver a jugar";
            }, 2000);
        }

        function createCoinAnimation() {
            const coin = document.createElement('div');
            coin.classList.add('coin-animation');
            coin.style.top = '50%';
            coin.style.left = '50%';
            document.body.appendChild(coin);
            setTimeout(() => coin.remove(), 1500);
        }

        btnStart.addEventListener("click", startGame);
        
        window.addEventListener("load", initBoard);
    </script>
@endsection
